export const meta = {
  "hero-centered": {
    type: "registry:block",
    title: "Hero — Centered",
    description: "Full-width centered hero with gradient headline, typewriter subtitle, CTA buttons, beam separator, and optional meteor shower.",
    categories: ["hero", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge", "gradient-text", "typewriter", "beam", "meteors"],
    filePath: "components/blocks/hero-centered.tsx",
  },
  "hero-split": {
    type: "registry:block",
    title: "Hero — Split",
    description: "Two-column hero with headline and feature bullets on the left, animated code preview card on the right.",
    categories: ["hero", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge", "glow-card", "gradient-text", "beam"],
    filePath: "components/blocks/hero-split.tsx",
  },
  pricing: {
    type: "registry:block",
    title: "Pricing Section",
    description: "Three-tier pricing table with monthly/annual toggle, feature lists, and highlighted popular plan.",
    categories: ["marketing", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge", "card", "switch", "label"],
    filePath: "components/blocks/pricing.tsx",
  },
  "feature-grid": {
    type: "registry:block",
    title: "Feature Grid",
    description: "Bento-style feature grid with glow cards, gradient text titles, and icon badges.",
    categories: ["marketing", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["glow-card", "gradient-text", "badge"],
    filePath: "components/blocks/feature-grid.tsx",
  },
  "feature-alternating": {
    type: "registry:block",
    title: "Feature — Alternating",
    description: "Three alternating feature rows with code previews. Left-right layout flips on odd rows.",
    categories: ["marketing", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["badge", "glow-card", "gradient-text", "beam"],
    filePath: "components/blocks/feature-alternating.tsx",
  },
  "cta-section": {
    type: "registry:block",
    title: "CTA Section",
    description: "Full-width call-to-action section with radial gradient background, meteors, and dual CTA buttons.",
    categories: ["marketing", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "gradient-text", "meteors"],
    filePath: "components/blocks/cta-section.tsx",
  },
  footer: {
    type: "registry:block",
    title: "Footer",
    description: "Three-column footer with brand tagline, link groups, legal links, and copyright.",
    categories: ["layout", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["separator"],
    filePath: "components/blocks/footer.tsx",
  },
  "auth-sign-in": {
    type: "registry:block",
    title: "Auth — Sign In",
    description: "Sign-in form with email/password, Google/GitHub social buttons, and forgot password link.",
    categories: ["auth", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["button", "input", "label", "card", "separator"],
    filePath: "components/blocks/auth-sign-in.tsx",
  },
  "auth-sign-up": {
    type: "registry:block",
    title: "Auth — Sign Up",
    description: "Sign-up form with name, email, password, terms checkbox, and social login options.",
    categories: ["auth", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["button", "input", "label", "card", "checkbox", "separator"],
    filePath: "components/blocks/auth-sign-up.tsx",
  },
  "dashboard-analytics": {
    type: "registry:block",
    title: "Dashboard — Analytics",
    description: "Analytics dashboard with metric cards, recent orders table, and top pages with progress bars.",
    categories: ["dashboard", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["card", "badge", "button", "progress", "avatar", "table", "select"],
    filePath: "components/blocks/dashboard-analytics.tsx",
  },
  "settings-page": {
    type: "registry:block",
    title: "Settings Page",
    description: "Settings layout with Profile, Security, Notifications, and Billing tabs.",
    categories: ["dashboard", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "input", "label", "card", "tabs", "switch", "select", "avatar", "separator", "badge"],
    filePath: "components/blocks/settings-page.tsx",
  },
  "ai-chat": {
    type: "registry:block",
    title: "AI Chat Interface",
    description: "Full-featured AI chat UI with message bubbles, model selector, copy button, and typing indicator.",
    categories: ["ai", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "input", "avatar", "scroll-area", "select", "badge"],
    filePath: "components/blocks/ai-chat.tsx",
  },
  footer: {
    type: "registry:block",
    title: "Footer",
    description: "Three-column footer with brand tagline, link groups, legal links, and copyright.",
    categories: ["layout", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["separator"],
    filePath: "components/blocks/footer.tsx",
  },
  pricing: {
    type: "registry:block",
    title: "Pricing Section",
    description: "Three-tier pricing table with monthly/annual toggle, feature lists, and highlighted popular plan.",
    categories: ["marketing", "blocks", "free"],
    dependencies: ["lucide-react"],
    registryDependencies: ["button", "badge", "card", "switch", "label"],
    filePath: "components/blocks/pricing.tsx",
  },
  faq: {
    type: "registry:block",
    title: "FAQ Section",
    description: "Accordion-based FAQ section with configurable questions and answers.",
    categories: ["marketing", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["accordion"],
    filePath: "components/blocks/faq.tsx",
  },
  stats: {
    type: "registry:block",
    title: "Stats Section",
    description: "Animated metric counters on glow cards with a beam separator. Numbers animate on scroll.",
    categories: ["marketing", "blocks", "free"],
    dependencies: ["@phosphor-icons/react"],
    registryDependencies: ["glow-card", "counter", "beam"],
    filePath: "components/blocks/stats.tsx",
  },
  testimonials: {
    type: "registry:block",
    title: "Testimonials Section",
    description: "Customer testimonial cards in a responsive grid with avatars and star ratings.",
    categories: ["marketing", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["glow-card", "avatar"],
    filePath: "components/blocks/testimonials.tsx",
  },
  "logo-cloud": {
    type: "registry:block",
    title: "Logo Cloud",
    description: "Infinite-scroll marquee of brand logos. Two rows, mirrored direction.",
    categories: ["marketing", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["marquee"],
    filePath: "components/blocks/logo-cloud.tsx",
  },
  "how-it-works": {
    type: "registry:block",
    title: "How It Works",
    description: "Three-step process section with numbered steps, icons, and a code snippet preview.",
    categories: ["marketing", "blocks", "free"],
    dependencies: ["@phosphor-icons/react"],
    registryDependencies: [],
    filePath: "components/blocks/how-it-works.tsx",
  },
  newsletter: {
    type: "registry:block",
    title: "Newsletter Section",
    description: "Email signup section with glow card, input, and submit button.",
    categories: ["marketing", "blocks", "free"],
    dependencies: [],
    registryDependencies: ["glow-card", "input", "button"],
    filePath: "components/blocks/newsletter.tsx",
  },
  "auth-forgot-password": {
    type: "registry:block",
    title: "Auth — Forgot Password",
    description: "Forgot password form with email input and reset link send confirmation.",
    categories: ["auth", "blocks", "free"],
    dependencies: ["@phosphor-icons/react"],
    registryDependencies: ["button", "input", "label", "card"],
    filePath: "components/blocks/auth-forgot-password.tsx",
  },
  "auth-verify-email": {
    type: "registry:block",
    title: "Auth — Verify Email",
    description: "Email verification screen with resend link and success state.",
    categories: ["auth", "blocks", "free"],
    dependencies: ["@phosphor-icons/react"],
    registryDependencies: ["button", "card"],
    filePath: "components/blocks/auth-verify-email.tsx",
  },
}
