export const meta = {
  "tilt-card": {
    title: "Tilt Card",
    description: "3D perspective tilt card with cursor-tracked glare highlight. Pure CSS transforms, no dependencies.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/tilt-card.tsx",
  },
  typewriter: {
    title: "Typewriter",
    description: "Animated typewriter with configurable typing/deleting speed, pause, and loop. Electric cursor blink.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/typewriter.tsx",
  },
  counter: {
    title: "Counter",
    description: "Spring-animated number counter with IntersectionObserver trigger, easing, and prefix/suffix support.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/counter.tsx",
  },
  "gradient-text": {
    title: "Gradient Text",
    description: "Animated gradient text with 5 variants: electric, aurora, fire, candy, and gold.",
    categories: ["text", "particles", "free"],
    dependencies: ["tailwind-variants"],
    filePath: "components/ui/gradient-text.tsx",
  },
  meteors: {
    title: "Meteors",
    description: "CSS-animated meteor shower effect. Drop into any relative-positioned container.",
    categories: ["background", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/meteors.tsx",
  },
  "confetti-button": {
    title: "Confetti Button",
    description: "Button that fires a canvas confetti burst on click. Wraps the core Button component.",
    categories: ["buttons", "particles", "free"],
    dependencies: [],
    registryDependencies: ["button"],
    filePath: "components/ui/confetti-button.tsx",
  },
  "shimmer-button": {
    title: "Shimmer Button",
    description: "Button with rotating conic-gradient shimmer border effect. Three variants: default, filled, dark.",
    categories: ["buttons", "particles", "free"],
    dependencies: ["tailwind-variants"],
    filePath: "components/ui/shimmer-button.tsx",
  },
  "glow-card": {
    title: "Glow Card",
    description: "Card with cursor-tracked radial spotlight glow. Configurable color, size, and opacity.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/glow-card.tsx",
  },
  "floating-dock": {
    title: "Floating Dock",
    description: "macOS-style dock with spring-scale magnification on hover. Fully keyboard accessible.",
    categories: ["navigation", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/floating-dock.tsx",
  },
  marquee: {
    title: "Marquee",
    description: "Infinite scroll marquee with configurable speed, direction, gap, and pause-on-hover.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/marquee.tsx",
  },
  beam: {
    title: "Beam",
    description: "Animated light beam that slides across a 1px separator line. Configurable color, speed, and delay.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/beam.tsx",
  },
  "glow-input": {
    title: "Glow Input",
    description: "Input with animated gradient border and drop-shadow glow on focus. Drop-in replacement for Input.",
    categories: ["forms", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/glow-input.tsx",
  },
  spotlight: {
    title: "Spotlight",
    description: "Card wrapper with a dual-layer radial spotlight that tracks the cursor. Drop-in replacement for GlowCard with a tighter, more intense beam.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/spotlight.tsx",
  },
  "border-beam": {
    title: "Border Beam",
    description: "Rotating conic-gradient border that sweeps around any container. Configurable colors, speed, and border width.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/border-beam.tsx",
  },
  "word-rotate": {
    title: "Word Rotate",
    description: "Cycles through an array of words with a fade + slide animation. Supports static prefix and suffix text.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/word-rotate.tsx",
  },
  "scroll-reveal": {
    title: "Scroll Reveal",
    description: "IntersectionObserver-powered fade-in wrapper. Configurable direction (up/down/left/right), distance, duration, delay, and once/repeat mode.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/scroll-reveal.tsx",
  },
  "magnetic-button": {
    title: "Magnetic Button",
    description: "Button that elastically follows the cursor with a configurable magnetic strength. Snaps back on mouse leave.",
    categories: ["buttons", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/magnetic-button.tsx",
  },
  ripple: {
    title: "Ripple Button",
    description: "Button that fires an expanding ripple at the click position. Configurable ripple color.",
    categories: ["buttons", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/ripple.tsx",
  },
  "flip-card": {
    title: "Flip Card",
    description: "3D CSS flip card with front and back slots. Supports horizontal/vertical flip and hover/click trigger.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/flip-card.tsx",
  },
  "shine-border": {
    title: "Shine Border",
    description: "Animated conic-gradient border with a multi-stop color sweep. Uses @property for smooth angle interpolation.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/shine-border.tsx",
  },
  "blur-fade": {
    title: "Blur Fade",
    description: "Viewport-triggered entrance animation: blurs out then fades in smoothly. Zero dependencies, respects prefers-reduced-motion.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/blur-fade.tsx",
  },
  "morphing-text": {
    title: "Morphing Text",
    description: "Cycles through an array of words with a smooth blur-morph transition. Configurable interval and CSS-only animation.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/morphing-text.tsx",
  },
  "retro-grid": {
    title: "Retro Grid",
    description: "Animated perspective grid floor background with scrolling lines. Pure CSS, zero JS. Drop into any relative container.",
    categories: ["background", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/retro-grid.tsx",
  },
  "text-shimmer": {
    title: "Text Shimmer",
    description: "Light shimmer that sweeps across text. Configurable speed, color, and background. Pure CSS animation.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/text-shimmer.tsx",
  },
  "sparkles-text": {
    title: "Sparkles Text",
    description: "Random sparkle SVG stars that appear and fade around your text. Configurable count, color, and speed.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/sparkles-text.tsx",
  },
  "animated-list": {
    title: "Animated List",
    description: "Staggered slide-up + fade-in entrance for list children. Configurable delay between items.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/animated-list.tsx",
  },
  "neon-border": {
    title: "Neon Border",
    description: "Card with a pulsing neon glow border. Configurable color. CSS box-shadow animation, no canvas required.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/neon-border.tsx",
  },
  "text-reveal": {
    title: "Text Reveal",
    description: "Text revealed by a sliding mask on scroll entry. Clean clip-path animation, viewport-triggered.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/text-reveal.tsx",
  },
  "glitch-text": {
    title: "Glitch Text",
    description: "Cyberpunk-style glitch effect with layered text-shadow offsets and random jitter keyframes.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/glitch-text.tsx",
  },
  "letter-swap": {
    title: "Letter Swap",
    description: "On hover, each letter scrambles through random characters before revealing the real letter. Configurable speed.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/letter-swap.tsx",
  },
  "scroll-progress": {
    title: "Scroll Progress",
    description: "Fixed-position thin progress bar showing how far the user has scrolled down the page. Configurable color and height.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/scroll-progress.tsx",
  },
  "wave-text": {
    title: "Wave Text",
    description: "Each character gets a staggered vertical wave animation. Configurable duration and amplitude. Pure CSS.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/wave-text.tsx",
  },
  "liquid-button": {
    title: "Liquid Button",
    description: "Button with a liquid blob that follows the cursor using a radial gradient fill effect. Smooth mousemove tracking.",
    categories: ["buttons", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/liquid-button.tsx",
  },
  "number-flow": {
    title: "Number Flow",
    description: "Smoothly animates between numeric values with digit-by-digit rolling animation. Supports prefix and suffix.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/number-flow.tsx",
  },
  "badge-shine": {
    title: "Badge Shine",
    description: "Status badge with an automatic shining light sweep. Three variants: default, pro, and new. Pure CSS.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/badge-shine.tsx",
  },
  "animate-in": {
    title: "Animate In",
    description: "Versatile viewport-triggered entrance animation wrapper. 7 variants: fade, slide-up/down/left/right, scale, rotate.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/animate-in.tsx",
  },
}
