export const meta = {
  "tilt-card": {
    title: "Tilt Card",
    description: "3D perspective tilt card with cursor-tracked glare highlight. Pure CSS transforms, no dependencies.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/tilt-card.tsx",
  },
  typewriter: {
    title: "Typewriter",
    description: "Animated typewriter with configurable typing/deleting speed, pause, and loop. Electric cursor blink.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/typewriter.tsx",
  },
  counter: {
    title: "Counter",
    description: "Spring-animated number counter with IntersectionObserver trigger, easing, and prefix/suffix support.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/counter.tsx",
  },
  "gradient-text": {
    title: "Gradient Text",
    description: "Animated gradient text with 5 variants: electric, aurora, fire, candy, and gold.",
    categories: ["text", "particles", "free"],
    dependencies: ["tailwind-variants"],
    filePath: "components/ui/gradient-text.tsx",
  },
  meteors: {
    title: "Meteors",
    description: "CSS-animated meteor shower effect. Drop into any relative-positioned container.",
    categories: ["background", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/meteors.tsx",
  },
  "confetti-button": {
    title: "Confetti Button",
    description: "Button that fires a canvas confetti burst on click. Wraps the core Button component.",
    categories: ["buttons", "particles", "free"],
    dependencies: [],
    registryDependencies: ["button"],
    filePath: "components/ui/confetti-button.tsx",
  },
  "shimmer-button": {
    title: "Shimmer Button",
    description: "Button with rotating conic-gradient shimmer border effect. Three variants: default, filled, dark.",
    categories: ["buttons", "particles", "free"],
    dependencies: ["tailwind-variants"],
    filePath: "components/ui/shimmer-button.tsx",
  },
  "glow-card": {
    title: "Glow Card",
    description: "Card with cursor-tracked radial spotlight glow. Configurable color, size, and opacity.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/glow-card.tsx",
  },
  "floating-dock": {
    title: "Floating Dock",
    description: "macOS-style dock with spring-scale magnification on hover. Fully keyboard accessible.",
    categories: ["navigation", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/floating-dock.tsx",
  },
  marquee: {
    title: "Marquee",
    description: "Infinite scroll marquee with configurable speed, direction, gap, and pause-on-hover.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/marquee.tsx",
  },
  beam: {
    title: "Beam",
    description: "Animated light beam that slides across a 1px separator line. Configurable color, speed, and delay.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/beam.tsx",
  },
  "glow-input": {
    title: "Glow Input",
    description: "Input with animated gradient border and drop-shadow glow on focus. Drop-in replacement for Input.",
    categories: ["forms", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/glow-input.tsx",
  },
  spotlight: {
    title: "Spotlight",
    description: "Card wrapper with a dual-layer radial spotlight that tracks the cursor. Drop-in replacement for GlowCard with a tighter, more intense beam.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/spotlight.tsx",
  },
  "border-beam": {
    title: "Border Beam",
    description: "Rotating conic-gradient border that sweeps around any container. Configurable colors, speed, and border width.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/border-beam.tsx",
  },
  "word-rotate": {
    title: "Word Rotate",
    description: "Cycles through an array of words with a fade + slide animation. Supports static prefix and suffix text.",
    categories: ["text", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/word-rotate.tsx",
  },
  "scroll-reveal": {
    title: "Scroll Reveal",
    description: "IntersectionObserver-powered fade-in wrapper. Configurable direction (up/down/left/right), distance, duration, delay, and once/repeat mode.",
    categories: ["layout", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/scroll-reveal.tsx",
  },
  "magnetic-button": {
    title: "Magnetic Button",
    description: "Button that elastically follows the cursor with a configurable magnetic strength. Snaps back on mouse leave.",
    categories: ["buttons", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/magnetic-button.tsx",
  },
  ripple: {
    title: "Ripple Button",
    description: "Button that fires an expanding ripple at the click position. Configurable ripple color.",
    categories: ["buttons", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/ripple.tsx",
  },
  "flip-card": {
    title: "Flip Card",
    description: "3D CSS flip card with front and back slots. Supports horizontal/vertical flip and hover/click trigger.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/flip-card.tsx",
  },
  "shine-border": {
    title: "Shine Border",
    description: "Animated conic-gradient border with a multi-stop color sweep. Uses @property for smooth angle interpolation.",
    categories: ["cards", "particles", "free"],
    dependencies: [],
    filePath: "components/ui/shine-border.tsx",
  },
}
