export const meta = {
  landing: {
    type: "registry:block",
    title: "Landing Page",
    description: "Complete SaaS landing page: hero, logo cloud, alternating features, stats, testimonials, pricing, FAQ, CTA, and footer. Install one component, get everything.",
    categories: ["template", "marketing", "free"],
    registryDependencies: ["hero-split", "logo-cloud", "feature-alternating", "stats", "testimonials", "pricing", "faq", "cta-section", "footer"],
    filePath: "components/templates/landing.tsx",
  },
  "saas-dashboard": {
    type: "registry:block",
    title: "SaaS Dashboard",
    description: "Analytics-focused dashboard with KPI stat cards and a detailed data table. Drop into any admin layout.",
    categories: ["template", "dashboard", "free"],
    registryDependencies: ["stats", "dashboard-analytics"],
    filePath: "components/templates/saas-dashboard.tsx",
  },
  auth: {
    type: "registry:block",
    title: "Auth Flow",
    description: "Sign-in, sign-up, forgot-password, and verify-email screens stitched together. Ready to wire to your auth provider.",
    categories: ["template", "auth", "free"],
    registryDependencies: ["auth-sign-in", "auth-sign-up", "auth-forgot-password", "auth-verify-email"],
    filePath: "components/templates/auth.tsx",
  },
  "pricing-page": {
    type: "registry:block",
    title: "Pricing Page",
    description: "Dedicated pricing page with a centered hero, three-tier pricing table, FAQ section, and CTA footer.",
    categories: ["template", "marketing", "free"],
    registryDependencies: ["hero-centered", "pricing", "faq", "cta-section", "footer"],
    filePath: "components/templates/pricing-page.tsx",
  },
  "docs-site": {
    type: "registry:block",
    title: "Docs Site",
    description: "Documentation shell with sticky top nav, sidebar navigation, main content area, on-page TOC, and footer.",
    categories: ["template", "documentation", "free"],
    registryDependencies: ["footer"],
    filePath: "components/templates/docs-site.tsx",
  },
  blog: {
    type: "registry:block",
    title: "Blog",
    description: "Blog index with header, hero, article list with author avatars, newsletter section, and footer.",
    categories: ["template", "content", "free"],
    registryDependencies: ["newsletter", "footer"],
    filePath: "components/templates/blog.tsx",
  },
}
