// Vue meta: keys are PascalCase (matching .vue filenames).
// name field gives the kebab slug used in registry output.
export const meta = {
  Button: {
    name: "button",
    title: "Button",
    description: "Accessible button with six variants. Electric-glow on the default variant.",
    categories: ["buttons", "core", "free"],
    dependencies: ["tailwind-variants"],
  },
  Input: {
    name: "input",
    title: "Input",
    description: "Text input with OKLCH-tuned focus ring and surface hierarchy.",
    categories: ["forms", "core", "free"],
    dependencies: [],
  },
  Textarea: {
    name: "textarea",
    title: "Textarea",
    description: "Textarea with matching input design language.",
    categories: ["forms", "core", "free"],
    dependencies: [],
  },
  Label: {
    name: "label",
    title: "Label",
    description: "Accessible form label.",
    categories: ["forms", "core", "free"],
    dependencies: [],
  },
  Badge: {
    name: "badge",
    title: "Badge",
    description: "Inline status badge with four variants.",
    categories: ["badges", "core", "free"],
    dependencies: ["tailwind-variants"],
  },
  Card: {
    name: "card",
    title: "Card",
    description: "Composable card with header, content, and footer slots.",
    categories: ["layout", "core", "free"],
    dependencies: [],
    subFiles: ["CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter"],
  },
  Separator: {
    name: "separator",
    title: "Separator",
    description: "Horizontal or vertical visual divider.",
    categories: ["layout", "core", "free"],
    dependencies: [],
  },
  Skeleton: {
    name: "skeleton",
    title: "Skeleton",
    description: "Animated placeholder for loading states.",
    categories: ["feedback", "core", "free"],
    dependencies: [],
  },
  Avatar: {
    name: "avatar",
    title: "Avatar",
    description: "Circular avatar with image and initials fallback.",
    categories: ["media", "core", "free"],
    dependencies: [],
  },
  Switch: {
    name: "switch",
    title: "Switch",
    description: "Accessible toggle switch with electric-cyan on state.",
    categories: ["forms", "core", "free"],
    dependencies: [],
  },
  Checkbox: {
    name: "checkbox",
    title: "Checkbox",
    description: "Accessible checkbox with electric-accent checked state.",
    categories: ["forms", "core", "free"],
    dependencies: [],
  },
  Tabs: {
    name: "tabs",
    title: "Tabs",
    description: "Context-based tab panels with keyboard navigation.",
    categories: ["navigation", "core", "free"],
    dependencies: [],
    subFiles: ["TabsList", "TabsTrigger", "TabsContent"],
  },
}
